/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/home/bscuser/scratch/install_mp/slurm_varios/lib/slurm";
char *default_slurm_config_file = "/home/bscuser/scratch/install_mp/slurm_conf/slurm.conf";
char *default_plugstack = "/home/bscuser/scratch/install_mp/slurm_conf/plugstack.conf";
